### PR TITLE
Simplifications.

### PR DESCRIPTION
**Pull request by ltratt**
A few simplifications I noticed for rstreediff. Note: all the tests pass, but I don't know if the tests touch all of these code paths. So it might be worth checking that.

### CODE REVIEW

**Comment by snim2** [comment]
OK, it will take me a little longer than usual to dig into this one...

**Comment by snim2** [comment]
OK, do you want to bring this branch up to date or shall I?

**Comment by ltratt** [comment]
It's my burden.

**Comment by ltratt** [comment]
OK, rebased. I'm not sure I'm very keen on this line though:

```rust
    let mut f = File::open(path).map_err(|e| ParseError::Io(e.to_string()))?;
```

It feels like we've converted it into a string too soon? However, changing that (or not) would be for another PR.

**Comment by snim2** [comment]
If you leave it as-is, that type is a `std::io::Error` and it seems a bit odd to me to have a `Io(std::io::Error)` in the `ParseError` enumeration. Also, I wanted to derive the `Debug` trait for `ParseError` and that can't be done with the `io::Error` in there.

**Comment by ltratt** [comment]
I think it's fine to just bundle up sub-errors into a big `enum` (I do it in lrtable/cfgrammar using `From`) without munging them. But maybe it's not a good idea here. Whether it is or not, it's not directly related to this PR, so let's discuss it next week, but not hold this PR up for it?

**Comment by snim2** [comment]
I agree. Do you want to squash or shall I merge as-is?

**Comment by ltratt** [comment]
I think the two commits stand nicely alone, so merge as-is from my perspective.

**Comment by snim2** [comment]
Great, thanks!

**Pull request merged**
