### PR TITLE
Reflect cfgrammar changes.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
OK, something's gone wrong here. Investigating.

**Comment by ltratt** [comment]
Ah, we're being stuffed, I think, by `Cargo.lock`. Trying now...

**Comment by snim2** [comment]
Do you want me to have a go?

**Comment by ltratt** [comment]
I'm on it...

**Comment by ltratt** [comment]
Yep, `Cargo.lock` was the culprit.

I'm still inclined to remove this from the development branch. I think it's definitely useful for release branches, but it's just obfuscatory on a day-to-day basis. But that's a different discussion, for a different day.

So, if you're happy with this PR, I guess I should squash.

**Comment by snim2** [comment]
The code looks fine, so please squash away.

**Comment by ltratt** [comment]
OK, squashed.

**Pull request merged**
